### ISSUE TITLE
Ur prejudice against python

### ISSUE THREAD

**Issue by DamieFC** [segfaultdev/bedd#1]
I get no java, but *c'mon*, Python is cool and good!

**Comment by DamieFC** [comment]
Basically, allow python files to be opened.

**Comment by DamieFC** [comment]
please

**Comment by DamieFC** [comment]
or I won't use ur editor

**Comment by DamieFC** [comment]
(yeah, blackmail and spam 😁)

**Comment by jmerono-saez** [comment]
First of all, this is not an issue, as that was intentionally done to help people's sanity by blocking python and Java files. And, as I explicitly said at the beginning of the README.md file:

> NOTE: This editor is not meant to be used by anyone other than me, @segfaultdev, as this is a project adapted to my usage and needs, so please don't submit any pull requests changing core functionality(specially the python and Java checks), and instead create your own fork. If you do so, please let me know so I can add a link to it below!

So, as I said, if you really don't care about your mental health and wanna remove the python and Java blocks, just make your own fork and I'll be more than happy to add it to the forks list, if you want.

**Comment by CaydendW** [comment]
I wouldn't call it good but it's not next level bad. Please seg. Listen to me.

**Comment by DamieFC** [comment]
ok add it to the list

**Comment by DamieFC** [comment]
wait C# hurts my head can we add that?

**Comment by jmerono-saez** [comment]
Although C# is a shitty language, it's by far not as bad as Java or python.
