### ISSUE TITLE
Add build and run macros/functions to editor

### ISSUE THREAD

**Issue by emma-eva** [segfaultdev/bedd#5]
I like your project. Can you plz implement compilers like gcc/clang/make/cmake etc on editor? It will helpful to coding on editor and compile and run...

If possible improve more for better editor... go ahead... thanks

**Comment by jmerono-saez** [comment]
Hey, glad you like it! Adding a way to build and run projects from within the editor is a thing I have thought of adding before, both by adding a builtin terminal (with PTYs or something) and by scripting and adding command macros to function keys. Be sure I'll work on it right when I finish implementing some more "crucial" features I'm still working on, like the undo stack of more complete syntax support.

**Comment by emma-eva** [comment]
also editor not responsive on mobile devices (neoterm/termux). make it good look on all os terminals. also remove `:` and add colors for line count bar and on background. Dark colors mode will be best. dont use white color.

I will use this project on my programming language. thanks again.

**Comment by emma-eva** [comment]
Use Makefile:
```
CC=cc
CFLAGS = -pedantic -Wall -Wextra -Wno-unused-parameter -I. -I./include
LDFLAGS = -lm

ifeq ($(OS),Windows_NT)
	CC = cc
	CFLAGS += -std=c89 -DWINDOWS
	LDFLAGS += -lws2_32 -lShlwapi
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		AR += ar
		CFLAGS += -std=c11 -DLINUX -D_XOPEN_SOURCE=700 -D_GNU_SOURCE
		LDFLAGS += -Wl,-rpath=./
	endif
	ifeq ($(UNAME_S),Darwin)
		AR += ar
		CFLAGS += -std=c11 -DDARWIN
	endif

	CFLAGS += -std=c11 -fPIC
	LDFLAGS += -ldl
endif

SRCS  = bd_config.c
SRCS += st_cobol.c
SRCS += bd_dialog.c
SRCS += st_js.c
SRCS += bd_explore.c
SRCS += st_md.c
SRCS += bd_global.c
SRCS += io_linux.c
SRCS += syntax.c
SRCS += bd_text.c
SRCS += match.c
SRCS += bd_view.c
SRCS += bd_welcome.c
SRCS += bedd.c
SRCS += st_c.c

OBJS = $(addprefix obj/,$(notdir $(SRCS:.c=.o)))

STATIC ?= 0
ifeq ($(STATIC),0)
	ifeq ($(OS),Windows_NT)
		LIB = libbedd.dll
	else
		LIB = libbedd.so
	endif
	LIBFLAGS = -L. -lbedd
else
	LIB = libbedd.a
	CFLAGS += -DSTATICLIB
endif

ifeq ($(OS),Windows_NT)
	install = @install bedd.exe libbedd.dll /bin
	clean = @rm -f bedd.exe libbedd.a libbedd.dll /bin/bedd.exe /bin/libbedd.dll
else
	install = @cp bedd $(PREFIX)/bin && chmod 755 $(PREFIX)/bin/bedd && cp libbedd.so $(PREFIX)/lib && chmod 644 $(PREFIX)/lib/libbedd.so
	clean = @rm -f bedd libbedd.a libbedd.so libbedd.dll $(PREFIX)/bin/bedd $(PREFIX)/lib/libbedd.so
endif

VPATH  = ./:./include
INCS := $(wildcard include/*.h)

.PHONY: all
all: mkdir bedd
mkdir: obj

obj:
	@mkdir obj

bedd: obj/bedd.o $(LIB) Makefile
	@$(CC) $(CFLAGS) obj/bedd.o $(LIB) $(LIBFLAGS) $(LDFLAGS) -o $@
#	@rm -rf obj
	@make install
	@echo "[Created]: bedd\n\nUse Command: ./bedd (For Shell) or ./bedd [file]\nInstall Command: make install\nTest Command: make test\nClean Command: make clean\n"

libbedd.a: $(OBJS) $(INCS) Makefile
	@echo "\n Please wait...\n"
	@$(AR) rcu $@ $(OBJS)
	@echo "[Created]: libbedd.a"

libbedd.so: $(OBJS) $(INCS) Makefile
	@echo "\n Please wait...\n"
	@$(CC) $(CFLAGS) $(LDFLAGS) -shared $(OBJS) -o $@
	@echo "[Created]: libbedd.so"

libbedd.dll: $(OBJS) $(INCS) Makefile
	@echo "\n Please wait...\n"
	@$(CC) $(CFLAGS) -shared $(OBJS) $(LDFLAGS) -o $@
	@echo "[Created]: libbedd.dll"

obj/%.o: %.c $(INCS) Makefile
	@$(CC) $(CFLAGS) -c $< -o $@
	@echo "[Creating Obj]: "$<

install:
	@$(install)
	@echo "[BeDD]: Installed Successfully!"

clean:
	@$(clean)
	@echo "[BeDD]: Cleabedd Successfully!"
```

**Comment by jmerono-saez** [comment]
First of all, thanks for taking your time into trying to help me with bedd!

I might check out how it looks on mobile terminal emulators and try to fix minor bugs if any, though keep in mind that bedd is meant to be used in full-blown computer setups and not on phones. And the colon and color thing on line numbers and backgrounds is just a subjective thing, personally I think it looks better as-is but maybe I could plan on adding UI customization onto configs. I'm also baffled by the dark/light mode thing you mentioned, bedd should only work so far on dark mode terminals (tried it on unconfigured xterm, with its light mode, and it looked horrible) and I don't finish to comprehend what you meant.

About the Makefile thing, that is something I'm not going to change no matter what, sorry if that makes it harder for you to use it.

Hope that helps!
